# Generated by Django 3.0.7 on 2020-07-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200729_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'alicilar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Sifarisler'},
        ),
    ]
