# Generated by Django 3.0.7 on 2020-07-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200729_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(blank=True, max_length=60)),
                ('navbar', models.CharField(blank=True, max_length=100)),
                ('navhome', models.CharField(blank=True, max_length=60)),
                ('navcart', models.CharField(blank=True, max_length=60)),
                ('navreg', models.CharField(blank=True, max_length=60)),
                ('navlogin', models.CharField(blank=True, max_length=60)),
                ('navlogout', models.CharField(blank=True, max_length=60)),
                ('navaccount', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ImegeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='upload/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
