# Generated by Django 3.0.7 on 2020-07-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_homepagesetting_imegeproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSetting',
        ),
        migrations.DeleteModel(
            name='ImegeProduct',
        ),
    ]
