# Generated by Django 3.0.7 on 2020-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_imageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(blank=True, max_length=60)),
                ('navbar', models.CharField(blank=True, max_length=100)),
                ('navhome', models.CharField(blank=True, max_length=60)),
                ('navcart', models.CharField(blank=True, max_length=60)),
                ('navreg', models.CharField(blank=True, max_length=60)),
                ('navlogin', models.CharField(blank=True, max_length=60)),
                ('navlogout', models.CharField(blank=True, max_length=60)),
                ('navaccount', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
