# Generated by Django 3.0.7 on 2020-07-29 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_homepagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesetting',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
