# Generated by Django 3.0.7 on 2020-07-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_homepagesetting_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name_plural': 'Mehsul sekil galerisi'},
        ),
    ]
